
wsmc = {
    0: "立案审批表",
    1: "抽样取证凭证",
    2: "行政(当场)处罚决定书（个人）",
    3: "现场检查方案",
    4: "先行登记保存证据审批表",
    5: "行政(当场)处罚决定书（单位）",
    6: "现场检查记录",
    7: "先行登记保存证据通知书",
    8: "缴纳罚款催告书",
    9: "现场处理措施决定书",
    10: "先行登记保存证据处理审批表",
    11: "加处罚款决定书",
    12: "责令限期整改指令书",
    13: "先行登记保存证据处理决定书",
    14: "延期(分期)缴纳罚款审批表",
    15: "整改复查意见书",
    16: "鉴定委托书",
    17: "延期(分期)缴纳罚款批准书",
    18: "行政强制审批表",
    19: "行政处罚告知书",
    20: "文书送达回执",
    21: "查封扣押决定书",
    22: "当事人陈述申辩笔录",
    23: "行政强制执行事先催告书",
    24: "查封扣押（场所、设施、财物）清单",
    25: "行政处罚听证告知书",
    26: "强制执行申请书",
    27: "延长查封扣押期限决定书",
    28: "行政处罚听证会通知书",
    29: "案件移送审批表",
    30: "查封扣押处理决定书",
    31: "听证笔录",
    32: "案件移送书",
    33: "停止供电（供应民用爆炸物品）通知书",
    34: "听证会报告书",
    35: "案件延期审批表",
    36: "停止供电（供应民用爆炸物品）决定书",
    37: "案件处理呈批表",
    38: "结案审批表",
    39: "恢复供电（供应民用爆炸物品）通知书",
    40: "行政处罚集体讨论记录",
    41: "案卷首页",
    42: "询问通知书",
    43: "行政处罚决定书（个人）",
    44: "卷内目录",
    45: "询问笔录",
    46: "行政处罚决定书（单位）",
    47: "勘验笔录",
    48: "巡查检查记录",
    49: "重大行政执法决定合法性审查意见书",
    50: "案件初审意见表",
    51: "案件调查报告",
    52: "重大行政执法决定法制审核审批表",
    53: "重大行政执法决定法制审核意见书",
    54: "重大行政执法决定合法性审查申请表",
    55: "重大行政执法决定法制审核意见书/吴江",

}

wszl = {
    0: "DocRegistCaseAudit",
    1: "DocNewCyqzpz",
    2: "DocNewScenePunishPerson",
    3: "DocNewCheckPlan",
    4: "DocNewXxdjbczjspb",
    5: "DocNewScenePunishCompany",
    6: "DocCheckResult",
    7: "DocNewXxdjbczjtzs",
    8: "DocNewJnfkcgs",
    9: "DocLocalDeal",
    10: "DocNewXxdjbczjclspb",
    11: "DocNewJcfkjds",
    12: "DocCorrect",
    13: "DocNewXxdjbczjcljds",
    14: "DocNewyqfqjnfkspb",
    15: "DocOpinion",
    16: "DocNewJdwts",
    17: "DocNewyqfqjnfkpzs",
    18: "DocNewXzqzspb",
    19: "DocNewXzcfgzs",
    20: "DocNewServiceReceipt",
    21: "DocNewCfkyjds",
    22: "DocNewDsrcssbbl",
    23: "DocNewxzqzzxsxcgs",
    24: "DocNewCfkyqdws",
    25: "DocNewXzcftzgzs",
    26: "DocNewqzcxsqs",
    27: "DocNewYccfkyqxjds",
    28: "DocNewXzcftzhtzs",
    29: "DocNewTransferApproval",
    30: "DocNewCfkycljds",
    31: "DocNewTzbl",
    32: "DocNewTransfer",
    33: "DocNewTzgdTzs",
    34: "DocNewTzhbgs",
    35: "DocNewajyqspb",
    36: "DocNewTzgdjds",
    37: "DocNewAjclcpb",
    38: "DocNewjaspb",
    39: "DocNewHfgdtzs",
    40: "DocNewXzcfjttljl",
    41: "DocNewajsy",
    42: "DocNewInquiryNotice",
    43: "DocNewXzcfjds_gr_fdc",
    44: "doc",
    45: "DocNewInquiryRecord",
    46: "DocNewXzcfjds_fdc",
    47: "DocNewInquestRecord",
    48: "DocXcResult",
    49: "DocNewFzscyjs",
    50: "DocNewFzcsyjb",
    51: "DocSurvey",
    52: "DocNewFzshspb",
    53: "DocNewFzshyjs",
    54: "DocNewFzscsqb",
    55: "DocNewFzshyjsWuJiang",
}

module_name = {
    0: "DOCREGISTCASEAUDIT",
    1: "DOCNEWCYQZPZ",
    2: "XZCFJDS_DC_GR",
    3: "DOCNEWCHECKPLAN",
    4: "DOCNEWXXDJBCZJSPB",
    5: "XZCFJDS_DC_DW",
    6: "XCJCJLPDF",
    7: "DOCNEWXXDJBCZJTZS",
    8: "DOCNEWJNFKCGS",
    9: "XCCLCSPDF",
    10: "DOCNEWXXDJBCZJCLSPB",
    11: "DOCNEWJCFKJDS",
    12: "ZLZGPDF",
    13: "DOCNEWXXDJBCZJCLJDS",
    14: "DOCNEWYQFQJNFKSPB",
    15: "ZGFCPDF",
    16: "DOCNEWJDWTS",
    17: "DOCNEWYQFQJNFKPZS",
    18: "DOCNEWXZQZSPB",
    19: "DOCNEWXZCFGZS",
    20: "DOCNEWSERVICERECEIPT",
    21: "DOCNEWCFKYJDS",
    22: "DOCNEWDSRCSSBBL",
    23: "DOCNEWXZQZZXSXCGS",
    24: "DOCNEWCFKYQDWS",
    25: "DOCNEWXZCFTZGZS",
    26: "DOCNEWQZCXSQS",
    27: "DOCNEWYCCFKYQXJDS",
    28: "DOCNEWXZCFTZHTZS",
    29: "DocNewTransferApproval",
    30: "DOCNEWCFKYCLJDS",
    31: "DOCNEWTZBL",
    32: "DocNewTransfer",
    33: "DOCNEWTZGDTZS",
    34: "DOCNEWTZHBGS",
    35: "DOCNEWAJYQSPB",
    36: "DOCNEWTZGDJDS",
    37: "DOCNEWAJCLCPB",
    38: "DOCNEWJASPB",
    39: "DOCNEWHFGDTZS",
    40: "DOCNEWXZCFJTTLJL",
    41: "DOCNEWAJSY",
    42: "DOCNEWINQUIRYNOTICE",
    43: "DOCNEWXZCFJDS_GR_FDC",
    44: "卷内目录.pdf",
    45: "DOCNEWINQUIRYRECORD",
    46: "DOCNEWXZCFJDS_FDC",
    47: "DOCNEWINQUESTRECORD",
    48: "XCJCJLPDF_Xc",
    49: "DocNewFzscyjs",
    50: "DocNewFzcsyjb",
    51: "DocSurvey",
    52: "DocNewFzshspb",
    53: "DocNewFzshyjs",
    54: "DOCNEWXZQZSPB",
    55: "DocNewFzshyjs",
}


def get_module_name_by_wszl(_wszl):
    id = list(wszl.values()).index(_wszl)
    return module_name[id]


def change(model):
    returnx = "".join([model[1][0].lower()+model[1][1:],
                       "=",
                       "ClassDocumentBasic",
                       "(",

                       '"'+model[0]+'"',
                       ",",
                       '"'+model[1]+'"',
                       ",",
                       '"'+model[2]+'"',
                       ")"
                       ])

    print(returnx)


if __name__ == '__main__':
    for t, k in enumerate(zip(wsmc.values(), wszl.values(), module_name.values())):
        change(k)

# for k,s_wsmc in list(enumerate(wsmc.values())):
#     # if k<3:
#         print(k,s_wsmc)
#         T_app_accessory_file.get_filename_modulename_distinct(s_wsmc)
